fastapi/sqlmodel

- .github/workflows/build-docs.yml
- .gitignore
- mkdocs.yml
🔧 Add MkDocs Material social cards
> 🔧 Add MkDocs Material social cards

- docs/release-notes.md
- docs_src/advanced/decimal/tutorial001.py
✏ Update decimal tutorial source for consistency
> ✏ Update decimal tutorial source for consistency

- docs/databases.md
- docs/tutorial/connect/create-connected-tables.md
- docs/tutorial/limit-and-offset.md
- docs/tutorial/select.md
- docs/tutorial/update.md
- docs/tutorial/where.md
Minor edit suggestions found while working through the documentation's tutorial.
> ✏ Fix multiple typos and some rewording

- pyproject.toml
- sqlmodel/main.py
⬆ Upgrade mypy, fix type annotations
> ⬆ Upgrade mypy, fix type annotations

- mkdocs.yml
- pyproject.toml
🔧 Upgrade MkDocs Material and update configs
> 🔧 Upgrade MkDocs Material and update configs

- .github/workflows/build-docs.yml
- .github/workflows/test.yml
💚 Only run CI on push when on master, to avoid duplicate runs on PRs
> 💚 Only run CI on push when on master, to avoid duplicate runs on PRs

- .github/workflows/test.yml
👷 Upgrade Codecov GitHub Action
> 👷 Upgrade Codecov GitHub Action

- .github/workflows/test.yml
> 👷 Add CI for Python 3.10

- docs/tutorial/index.md
Fix typo in tutorial index: refreshed -> refresher
> ✏ Fix typo in `docs/tutorial/index.md`

- .github/workflows/build-docs.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
> ⬆️ Upgrade Poetry to version `==1.2.0b1`

- .github/dependabot.yml
👷 Add dependabot for GitHub Actions
> 👷 Add dependabot for GitHub Actions

- docs/tutorial/fastapi/tests.md
> ✏ Fix typo in `docs/tutorial/fastapi/tests.md`

- .github/dependabot.yml
> 👷 Update Dependabot config

- pyproject.toml
➕ Add extra dev dependencies for MkDocs Material
> ➕ Add extra dev dependencies for MkDocs Material

- .github/workflows/smokeshow.yml
- .github/workflows/test.yml
- README.md
- docs/index.md
- pyproject.toml
- scripts/test-cov-html.sh
- scripts/test.sh
👷 Move from Codecov to Smokeshow
> 👷 Move from Codecov to Smokeshow

- .github/workflows/smokeshow.yml
🔧 Update Smokeshow coverage threshold
> 🔧 Update Smokeshow coverage threshold

- .github/workflows/build-docs.yml
- .github/workflows/preview-docs.yml
- scripts/zip-docs.sh
👷 Refactor CI artifact upload/download for docs previews
> 👷 Refactor CI artifact upload/download for docs previews

- .github/DISCUSSION_TEMPLATE/questions.yml
🔧 Add template for GitHub Discussion questions and update issues template
> 🔧 Add template for GitHub Discussion questions and update issues template

- docs/help.md
> 📝 Update help SQLModel docs

- .github/workflows/latest-changes.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
👷 Update CI debug mode with Tmate
> 👷 Update CI debug mode with Tmate

- .github/workflows/deploy-docs.yml
👷 Update docs deployments to Cloudflare
> 👷 Update docs deployments to Cloudflare

- docs/tutorial/fastapi/relationships.md
- docs/tutorial/fastapi/session-with-dependency.md
- docs/tutorial/fastapi/teams.md
- docs_src/tutorial/fastapi/app_testing/tutorial001/main.py
- docs_src/tutorial/fastapi/relationships/tutorial001.py
- docs_src/tutorial/fastapi/session_with_dependency/tutorial001.py
- docs_src/tutorial/fastapi/teams/tutorial001.py
🎨 Update docs format and references with pre-commit and Ruff
> 🎨 Update docs format and references with pre-commit and Ruff

- pyproject.toml
> ⬆️ Upgrade mypy manually

- mkdocs.yml
- scripts/docs-live.sh
🔧 Show line numbers in docs during local development
> 🔧 Show line numbers in docs during local development

- .github/workflows/build-docs.yml
- sqlmodel/sql/expression.py
- sqlmodel/sql/expression.py.jinja2
- tests/conftest.py
👷 Fix GitHub Actions build docs filter paths for GitHub workflows
> 👷 Fix GitHub Actions build docs filter paths for GitHub workflows

- .pre-commit-config.yaml
- pyproject.toml
⬆️ Upgrade Ruff version and configs
> ⬆️ Upgrade Ruff version and configs

- mkdocs.insiders.yml
🔧 Update MkDocs, disable cards while I can upgrade to the latest MkDocs Material, that fixes an issue with social cards
> 🔧 Update MkDocs, disable cards while I can upgrade to the latest MkDocs Material, that fixes an issue with social cards

- mkdocs.insiders.yml
🔧 Re-enable MkDocs Material Social plugin
> 🔧 Re-enable MkDocs Material Social plugin

- .github/workflows/test-redistribute.yml
👷 Tweak CI for test-redistribute, add needed env vars for slim
> 👷 Tweak CI for test-redistribute, add needed env vars for slim

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/smokeshow.yml
- .github/workflows/test.yml
👷 Update GitHub Actions to download and upload artifacts
> 👷 Update GitHub Actions to download and upload artifacts

- pyproject.toml
⬆️ Update minimum SQLAlchemy version to 2.0.14 as that one includes `TryCast` used internally
> ⬆️ Update minimum SQLAlchemy version to 2.0.14 as that one includes `TryCast` used internally

- docs/tutorial/index.md
✏️ Update pip installation command in tutorial
> ✏️ Update pip installation command in tutorial

- docs/tutorial/create-db-and-table-with-db-browser.md
✏️ Add missing step in `create-db-and-table-with-db-browser.md`
> ✏️ Add missing step in `create-db-and-table-with-db-browser.md`

- docs/tutorial/automatic-id-none-refresh.md
- docs/tutorial/connect/create-connected-rows.md
- docs/tutorial/create-db-and-table.md
- docs/tutorial/relationship-attributes/create-and-update-relationships.md
- docs/tutorial/where.md
> 📝 Update docs 

- mkdocs.yml
> 🔧 Enable auto dark mode

- docs/css/termynal.css
>  💄 Update Termynal line-height

- data/members.yml
- docs/about/index.md
- docs/css/custom.css
- docs/learn/index.md
- docs/management-tasks.md
- docs/management.md
- docs/resources/index.md
- docs/tutorial/index.md
- mkdocs.yml
📝 Add docs about repo management and team
> 📝 Add docs about repo management and team

- data/members.yml
> 🔧 Update members

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/privileged.yml
- .github/workflows/issue-manager.yml
- CITATION.cff
- README.md
- docs/help.md
- docs/index.md
- docs/management-tasks.md
- mkdocs.yml
- pyproject.toml
📝 Update links from github.com/tiangolo/sqlmodel to github.com/fastapi/sqlmodel
> 📝 Update links from github.com/tiangolo/sqlmodel to github.com/fastapi/sqlmodel

- docs_src/tutorial/automatic_id_none_refresh/annotations/en/tutorial002.md
- docs_src/tutorial/delete/annotations/en/tutorial002.md
- docs_src/tutorial/fastapi/app_testing/tutorial001/annotations/en/test_main_004.md
- docs_src/tutorial/fastapi/app_testing/tutorial001_py310/annotations/en/test_main_004.md
- docs_src/tutorial/fastapi/app_testing/tutorial001_py39/annotations/en/test_main_004.md
- docs_src/tutorial/select/annotations/en/tutorial002.md
- docs_src/tutorial/update/annotations/en/tutorial002.md
- docs_src/tutorial/update/annotations/en/tutorial004.md
📝 Update admonitions in annotations
> 📝 Update admonitions in annotations

- .github/workflows/add-to-project.yml
👷 Update GitHub Action add-to-project
> 👷 Update GitHub Action add-to-project

- .github/workflows/labeler.yml
👷 Update labeler GitHub Actions permissions and dependencies
> 👷 Update labeler GitHub Actions permissions and dependencies

- .github/labeler.yml
- .github/workflows/labeler.yml
👷 Update configs for GitHub Action labeler, to add only one label
> 👷 Update configs for GitHub Action labeler, to add only one label

- .github/workflows/test.yml
👷 Update Python version for coverage
> 👷 Update Python version for coverage

- scripts/lint.sh
> 🔧 Update lint script

- docs/virtual-environments.md
- scripts/lint.sh
✏️ Fix a typo in `docs/virtual-environments.md`
> ✏️ Fix a typo in `docs/virtual-environments.md`

- .github/workflows/test.yml
👷 Fix coverage processing in CI, one name per matrix run
> 👷 Fix coverage processing in CI, one name per matrix run

- docs/tutorial/one.md
> ✏️ Fix typo in documentation

- scripts/format.sh
🔨 Update script to standardize format
> 🔨 Update script to standardize format

- mkdocs.yml
- requirements-docs.txt
➕ Add docs dependency markdown-include-variants
> ➕ Add docs dependency markdown-include-variants

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/smokeshow.yml
- .github/workflows/test.yml
- requirements-github-actions.txt
> 👷 Use uv in CI

- .github/workflows/issue-manager.yml
👷 Update issue manager workflow
> 👷 Update issue manager workflow

- docs/databases.md
- docs/db-to-code.md
- docs/install.md
> 📝 Fix internal links in docs

- docs/tutorial/create-db-and-table.md
📝 Update includes for `docs/tutorial/create-db-and-table.md`
> 📝 Update includes for `docs/tutorial/create-db-and-table.md`

- data/members.yml
> 🔧 Update team members

- docs/advanced/decimal.md
📝 Update fenced code in Decimal docs for consistency
> 📝 Update fenced code in Decimal docs for consistency

- .github/workflows/test.yml
- scripts/test.sh
This reverts commit 759220d5928af4a01c205a039eb9826456a475cd.
> 👷 Revert "Add Codecov to CI, Smokeshow/Cloudflare has been flaky lately (#1303)"
